name: reforge
channels:
  - conda-forge
dependencies:
  - python
  - cython
  - numpy 2.2.3
  - vermouth 0.13
  - mdanalysis
  - matplotlib
  - memory_profiler
  - setuptools
  - openmm
  - cupy
  - selenium
  - selenium-manager
  - pandas
  - packaging
  - pytest
  - setuptools